### ISSUE TITLE
"error" field in JSON response

### ISSUE THREAD

**Issue by iambenkay** [MartinsOnuoha/countriesAndCitiesAPI#11]
Good day. Nice work you're doing here. I was going through the documentation and I noticed you add the `error` field to every JSON response. I want to know why exactly. because I assume that errors can be conveyed with appropriate error codes (status codes greater than or equal to 400). I believe that is the semantic use of those status codes. Is there a special reason you set the error field?

**Comment by MartinsOnuoha** [comment]
@iambenkay Thanks for the observation. Yeah, there's a reason, simplicity really. Per the `JSON:API` specification, dealing with errors would require the using the `Error` Object property that would returns an array of error objects containing the `status`,  `code` and `detail` fields, this would be the ideal design for REST apis like this one, however, for simplicity instead of having the entire Error array object, I decided to make it root level field and give it the value of it's child property `status` (true, false) - so it's readable enough. 

so instead of having this:
```json
{
   error: [{ "status": false, "code":  401, "details": "unauthorized" }, {...}, {...}],
   data: []
}
```

we have this:
```json
{
  error: false,
  data: []
}
```

It's mostly a design for simplicity than architecture

**Comment by iambenkay** [comment]
Alright. thanks for clearing that up

**Comment by iambenkay** [comment]
I'll be closing this issue now

**Comment by MartinsOnuoha** [comment]
You won't have to stress about closing it manually, once we merge the related PR, it'll be closed automatically 🎉
