### ISSUE TITLE
Would it be possible to add a "top 5 cities" or filtering by population?

### ISSUE THREAD

**Issue by alexgarciab** [MartinsOnuoha/countriesAndCitiesAPI#9]
Would it be possible to add a top 5 cities (per country) endpoint to be able to retrieve the most populated cities? Or even better, add a filter to get only the cities with more than X number of people. Thanks

**Comment by MartinsOnuoha** [comment]
@alexgarciab Alright, let's have this as an open issue, our likely options would be to carry out a data collection, or use a realtime API, because of the volatile nature of those figures.
- if we collected the data, we might soon enough have out of date figures and would have to update them manually.
Using a 3rd party API would be our best bet.

**Comment by alexgarciab** [comment]
This one is a good one: https://public.opendatasoft.com/explore/dataset/geonames-all-cities-with-a-population-1000/table/?disjunctive.country - We are going to use it

**Comment by MartinsOnuoha** [comment]
Hey @alexgarciab 
I resolved to use the datahub API. `https://datahub.io/core/population`, I'll make a PR later today.

**Comment by alexgarciab** [comment]
Did you manage to get population per city or just per country?

**Comment by MartinsOnuoha** [comment]
@alexgarciab a PR has been created for this issue, feel free to have a look.
